spring:
    datasource:
        url: jdbc:mysql://localhost:3306/plecodb?useSSL=false
        username: plecouser
        password: plecoPa$$1

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                show_sql: true
                format_sql: true

#File Uploading
#5MB = 5120KB but with request header this varies few KB so adding a safe margin , need to change at nginx server as well
    servlet:
        multipart:
            max-file-size:  8000KB
            max-request-size: 8000KB
            enabled: true
#server:
#    tomcat:
#      max-http-post-size: 10MB
#      max-swallow-size: 10MB
server:
  use-forward-headers: true
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
#  http:
#    auto-config: true
#    disable-url-rewriting: true
#

facebook:
  client:
    clientId: 285080992197803
    clientSecret: 51cc18c22e11fd3fc5aeb1175b052859
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope:
      - email
      - user_link
      - public_profile
  resource:
    userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250),link
github:
  client:
    clientId: 400e01a24d62ae39
    clientSecret: 5d3a59965b562cdc93c5ffa2a4856e8133f6f75c
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope:
      - user:email
      - read:user
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate:
          type: DEBUG
    com.ciperlabs: DEBUG


#Path to excel files stored folder
storage:
    Document:
        root: /home/plecoadm/unicode-pleco/Documents/
        uploadExcel: uploaded/excel/
        uploadDocx: uploaded/docx/
        uploadPDF: uploaded/pdf/
        uploadDoc: uploaded/doc/
        convertedExcel: converted/excel/
        convertedDocx: converted/docx/
        pdfToWordPDF: pdfToWord/pdf/
        pdfToWordDocx: pdfToWord/docx/


pdftoword:
    API:  "http://localhost:5000/api/converter"

jodconverter:
  local:
    enabled: true
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages


